import { SchoolContactInfo, TimelineMilestone, NewsItem, SchoolEvent, GalleryPhoto } from '../types';

export const SCHOOL_INFO: SchoolContactInfo = {
  schoolName: "EMAUDO SECONDARY SCHOOL",
  established: 1980,
  founder: "Professor Ambrose Folorunsho Alli (Governor of Bendel State, 1979–1983)",
  addressLines: [
    "178 Osimen Street, Emaudo",
    "Ekpoma, Edo State",
    "Nigeria"
  ],
  fullAddress: "178 Osimen Street, Emaudo, Ekpoma, Edo State, Nigeria",
  whatsappDisplay: "+234 813 911 1765",
  whatsappRaw: "2348139111765",
  whatsappMessage: "Hello Emaudo Secondary School, I would like to make an enquiry.",
  whatsappUrl: "https://wa.me/2348139111765?text=Hello%20Emaudo%20Secondary%20School%2C%20I%20would%20like%20to%20make%20an%20enquiry.",
  phoneDisplay: "07018543531",
  phoneTel: "tel:07018543531",
  email: "[EMAIL ADDRESS]",
  essosaUrl: "https://emaudooldstudents.org/",
  essosaHistoryUrl: "https://emaudooldstudents.org/about/history/",
  essosaGalleryUrl: "https://emaudooldstudents.org/gallery/",
};

export const VERIFIED_HISTORY_MILESTONES: TimelineMilestone[] = [
  {
    id: "milestone-1980",
    year: "1980",
    title: "Establishment of Emaudo Secondary School",
    subtitle: "Under the Administration of Professor Ambrose Folorunsho Alli",
    description: "Emaudo Secondary School was established in 1980 in Emaudo, Ekpoma, in the former Bendel State of Nigeria. The school was founded during the administration of Professor Ambrose Folorunsho Alli, who served as Governor of Bendel State from 1979 to 1983, as part of the visionary expansion of secondary education associated with his educational policies and free-education programme.",
    tag: "Foundation & Heritage",
    iconName: "flag",
    photoPlaceholder: "Historical 1980 Founding Archive Placeholder",
    verified: true,
  },
  {
    id: "milestone-1985",
    year: "1985",
    title: "First Graduating Class",
    subtitle: "Pioneering Students Complete Secondary Education",
    description: "Five years following its establishment, the school reached a historic milestone in 1985 as its pioneering cohort of students completed their secondary school studies and officially graduated, setting the precedent for academic dedication in Ekpoma.",
    tag: "Pioneer Graduation",
    iconName: "graduation",
    photoPlaceholder: "1985 Pioneer Graduating Class Archive Placeholder",
    verified: true,
  },
  {
    id: "milestone-1986",
    year: "1986",
    title: "Progression to Grade-One School",
    subtitle: "Rapid Academic & Structural Elevation",
    description: "Demonstrating swift institutional growth, academic standard improvements, and instructional quality, by 1986 Emaudo Secondary School progressed from a grade-three school to a recognized grade-one school.",
    tag: "Grade 1 Accreditation",
    iconName: "award",
    photoPlaceholder: "1986 Grade-One Elevation Records Placeholder",
    verified: true,
  },
  {
    id: "milestone-tradition",
    year: "1987 - 2016",
    title: "Consolidation of Science & Arts Heritage",
    subtitle: "Decades of Rigorous Secondary Education",
    description: "Throughout the late 1980s, 1990s, and 2000s, Emaudo Secondary School developed a robust reputation for training students in both Science and Arts disciplines, preparing thousands of Esan youth for higher education, leadership, and national service.",
    tag: "Academic Growth",
    iconName: "book",
    photoPlaceholder: "Academic Archives Placeholder",
    verified: true,
  },
  {
    id: "milestone-2017",
    year: "2017",
    title: "Ultra-Modern Science Laboratory Complex",
    subtitle: "Inauguration Supported by Chevron & Partners",
    description: "In 2017, an ultra-modern science laboratory complex was constructed at Emaudo Secondary School with the support of Chevron and its joint-venture partners. The facility was officially inaugurated to provide state-of-the-art physics, chemistry, and biology learning environments for students.",
    tag: "Science & Infrastructure",
    iconName: "microscope",
    photoPlaceholder: "2017 Chevron Science Laboratory Complex Photo Placeholder",
    verified: true,
  },
  {
    id: "milestone-present",
    year: "Present Day",
    title: "More Than Four Decades of Educational Heritage",
    subtitle: "45+ Years of Excellence and Character Formation",
    description: "Today, Emaudo Secondary School stands tall as an enduring pillar of secondary education in Ekpoma, backed by a global network of alumni through ESSOSA and committed to discipline, academic excellence, and community leadership.",
    tag: "Enduring Legacy",
    iconName: "sparkles",
    photoPlaceholder: "Modern School Campus & Community Placeholder",
    verified: true,
  }
];

export const SAMPLE_NEWS: NewsItem[] = [
  {
    id: "news-1",
    title: "Orientation and Welcome for New Academic Session",
    category: "School News",
    date: "Sample Term Notice",
    summary: "Welcoming students, teaching staff, and parents as academic activities commence for the session.",
    content: "Students and teachers gather as the new term begins with renewed focus on academic discipline, continuous assessment, and science laboratory practicals. Note: Exact term dates and schedules should be confirmed directly with the school administration.",
    isSample: true,
  },
  {
    id: "news-2",
    title: "Science Laboratory Practical Sessions Underway",
    category: "Academic",
    date: "Sample Academic Notice",
    summary: "Senior secondary science students engage in weekly laboratory experiments in physics, chemistry, and biology.",
    content: "Utilizing the dedicated science laboratory facility inaugurated with corporate support, students undertake practical examinations and curriculum-aligned laboratory experiments under supervised instruction.",
    isSample: true,
  },
  {
    id: "news-3",
    title: "ESSOSA Alumni Engagement & School Development Dialogue",
    category: "Alumni",
    date: "Sample Alumni Notice",
    summary: "The Emaudo Secondary School Old Students Association continues outreach to support school initiatives.",
    content: "Alumni members across Nigeria and the diaspora maintain active collaboration through ESSOSA to foster educational development and mentorship for current students. Visit the official alumni website at emaudooldstudents.org for alumni updates.",
    isSample: true,
  },
  {
    id: "news-4",
    title: "Inter-House Sports and Extracurricular Preparation",
    category: "Events",
    date: "Sample Sports Notice",
    summary: "Athletic and extracurricular programmes fostering teamwork, physical fitness, and student sportsmanship.",
    content: "House teams begin track and field preparations alongside debate and cultural club activities. Dates and schedules are tentative sample schedules to be confirmed by the school.",
    isSample: true,
  }
];

export const SAMPLE_EVENTS: SchoolEvent[] = [
  {
    id: "event-1",
    title: "Term Resumption & Assembly",
    category: "School Ceremonies",
    schedule: "Term Beginning (Sample Date)",
    location: "Main Assembly Hall, Emaudo Campus",
    description: "General school assembly, class allocations, timetable distribution, and administrative address.",
    isSample: true,
  },
  {
    id: "event-2",
    title: "Mid-Term Academic Progress Assessments",
    category: "Academic Events",
    schedule: "Mid-Term Week (Sample Schedule)",
    location: "Classrooms & Science Lab",
    description: "Continuous assessment tests for Junior and Senior secondary students across all registered subjects.",
    isSample: true,
  },
  {
    id: "event-3",
    title: "Inter-House Athletics & Sports Competition",
    category: "Sports",
    schedule: "Annual Sports Week (Sample Schedule)",
    location: "School Sports Ground",
    description: "Track and field competitions, football tournament, and relay events for all student houses.",
    isSample: true,
  },
  {
    id: "event-4",
    title: "Parent-Teacher Association (PTA) General Meeting",
    category: "Parent Meetings",
    schedule: "Termly Meeting (Sample Schedule)",
    location: "Emaudo School Hall",
    description: "Open forum for parents, guardians, and teachers to discuss student welfare and academic advancement.",
    isSample: true,
  },
  {
    id: "event-5",
    title: "ESSOSA Alumni Mentorship & Homecoming Session",
    category: "Alumni Events",
    schedule: "Annual ESSOSA Calendar (Sample Date)",
    location: "Emaudo Secondary School Campus",
    description: "Old students visit the school for career guidance sessions, awards, and alumni collaborative projects.",
    isSample: true,
  }
];

export const GALLERY_ITEMS: GalleryPhoto[] = [
  {
    id: "gal-1",
    title: "Ultra-Modern Science Laboratory Complex",
    category: "Science Laboratory",
    description: "Constructed with support from Chevron and partners, and inaugurated in 2017 to foster physics, chemistry, and biology excellence.",
    date: "2017 Inauguration & Active",
    source: "Emaudo School Infrastructure Archive",
    placeholderLabel: "Science Laboratory Complex (Chevron 2017 Project)",
    accentColor: "from-blue-900 to-indigo-900",
  },
  {
    id: "gal-2",
    title: "School Founder — Prof. Ambrose Folorunsho Alli",
    category: "Historical Photos",
    description: "Governor of Bendel State (1979–1983), visionary leader behind the 1980 establishment of secondary schools across Bendel State.",
    date: "1980 Founding Era",
    source: "Historical Bendel State Archive",
    placeholderLabel: "Prof. Ambrose Folorunsho Alli Founder Archive Placeholder",
    accentColor: "from-slate-900 to-amber-950",
  },
  {
    id: "gal-3",
    title: "Main Campus & Administrative Block",
    category: "School",
    description: "Emaudo Secondary School campus grounds along Osimen Street, Emaudo, Ekpoma, Edo State.",
    date: "Campus Overview",
    source: "Emaudo Campus Registry",
    placeholderLabel: "School Campus & Academic Blocks Placeholder",
    accentColor: "from-blue-950 to-slate-900",
  },
  {
    id: "gal-4",
    title: "Students in Academic Learning",
    category: "Students",
    description: "Classroom instruction, peer discussion, and focused learning across Junior and Senior secondary levels.",
    date: "Academic Session",
    source: "Student Affairs Archive",
    placeholderLabel: "Classroom Learning & Student Activities Placeholder",
    accentColor: "from-emerald-950 to-blue-950",
  },
  {
    id: "gal-5",
    title: "ESSOSA Alumni Homecoming & Engagements",
    category: "Alumni",
    description: "Members of Emaudo Secondary School Old Students Association visiting the campus and supporting projects.",
    date: "Alumni Network",
    source: "ESSOSA Official Archives (emaudooldstudents.org)",
    placeholderLabel: "ESSOSA Old Students Association Engagements Placeholder",
    accentColor: "from-amber-950 to-slate-900",
  },
  {
    id: "gal-6",
    title: "Annual Sports & Athletics Competitions",
    category: "Sports",
    description: "Student athletes participating in track, field, football, and inter-house athletic championships.",
    date: "Sports Archive",
    source: "Extracurricular Affairs",
    placeholderLabel: "Inter-House Sports & Athletic Competitions Placeholder",
    accentColor: "from-orange-950 to-blue-950",
  },
  {
    id: "gal-7",
    title: "1985 Pioneer Graduating Class Legacy",
    category: "Historical Photos",
    description: "Commemorating the first graduating set of 1985 who set the academic standard for generations to follow.",
    date: "1985 Milestone",
    source: "Historical School Records",
    placeholderLabel: "1985 Pioneer Graduating Class Record Placeholder",
    accentColor: "from-slate-900 to-blue-950",
  },
  {
    id: "gal-8",
    title: "1986 Grade-One Elevation Commemoration",
    category: "Historical Photos",
    description: "The historical transition of Emaudo Secondary School from a Grade 3 institution to a premier Grade 1 school.",
    date: "1986 Milestone",
    source: "Ministry of Education Historical Archive",
    placeholderLabel: "1986 Grade-One Elevation Historical Record Placeholder",
    accentColor: "from-blue-950 to-amber-950",
  }
];
